services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog
    restart: unless-stopped

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongodb
      - zookeeper
    # env_file:
    #   - ./backend/.env  --> if you want to upload your .env then uncomment and add .env here and comment whole environment below.
    environment:
      - PORT="port your want to run"
      - REDIS_HOST="your redis host"
      - REDIS_PORT="your redis port"
      - LOG_LEVEL="info"
      - ZK_SERVER="your zookeeper server URL"
      - MONGODB_URI="your mongodb URL"
      - BASE_URL="your base URL"
    restart: unless-stopped

volumes:
  redis-data:
  zookeeper-data:
  zookeeper-datalog:
  mongodb-data:
