version: "3.8"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog
    restart: unless-stopped

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mongodb
      - zookeeper
    environment:
      - PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
      - ZK_SERVER=zookeeper:2181
      - MONGODB_URI=mongodb://mongodb:27017/DistroURL
      - BASE_URL=distro-url.vercel.app
    restart: unless-stopped

volumes:
  redis-data:
  zookeeper-data:
  zookeeper-datalog:
  mongodb-data:
