name: Sync Backend Subtree

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main

jobs:
  sync-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Push backend subtree to backend repo
        run: |
          git remote add backend-origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/alucard017/DistroURL-backend.git
          git subtree push --prefix=backend backend-origin main
