name: Sync Subtrees

on:
  push:
    paths:
      - "frontend/**"
      - "backend/**"
    branches:
      - main

jobs:
  sync-subtrees:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add remotes
        run: |
          git remote | grep frontend-origin || git remote add frontend-origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/alucard017/DistroURL-frontend.git
          git remote | grep backend-origin || git remote add backend-origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/alucard017/DistroURL-backend.git

      - name: Split frontend subtree and push
        run: |
          git subtree split --prefix=frontend -b temp-frontend
          git push frontend-origin temp-frontend:main --force

      - name: Split backend subtree and push
        run: |
          git subtree split --prefix=backend -b temp-backend
          git push backend-origin temp-backend:main --force
