name: Sync Subtrees

on:
  push:
    paths:
      - "frontend/**"
      - "backend/**"
    branches:
      - main

jobs:
  sync-subtrees:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Sync Frontend Repo
        if: contains(github.event.head_commit.message, 'frontend') || contains(github.event.head_commit.message, 'Frontend')
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/alucard017/DistroURL-frontend.git frontend-temp
          rsync -av --delete frontend/ frontend-temp/
          cd frontend-temp
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-sync frontend from monorepo" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/alucard017/DistroURL-frontend.git

      - name: Sync Backend Repo
        if: contains(github.event.head_commit.message, 'backend') || contains(github.event.head_commit.message, 'Backend')
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/alucard017/DistroURL-backend.git backend-temp
          rsync -av --delete backend/ backend-temp/
          cd backend-temp
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto-sync backend from monorepo" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/alucard017/DistroURL-backend.git
