name: Sync Subtrees

on:
  push:
    paths:
      - "frontend/**"
      - "backend/**"
    branches:
      - main

jobs:
  sync-subtrees:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Split & push frontend to DistroURL-frontend
        if: contains(github.event.head_commit.message, 'frontend') || contains(github.event.head_commit.message, 'Frontend')
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote add frontend-origin https://x-access-token:${GH_PAT}@github.com/alucard017/DistroURL-frontend.git
          git subtree split -P frontend -b temp-frontend
          git push -f frontend-origin temp-frontend:main

      - name: Split & push backend to DistroURL-backend
        if: contains(github.event.head_commit.message, 'backend') || contains(github.event.head_commit.message, 'Backend')
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote add backend-origin https://x-access-token:${GH_PAT}@github.com/alucard017/DistroURL-backend.git
          git subtree split -P backend -b temp-backend
          git push -f backend-origin temp-backend:main
