name: Sync Subtrees

on:
  push:
    paths:
      - "frontend/**"
      - "backend/**"
    branches:
      - main

jobs:
  sync-subtrees:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Setup Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Split and push frontend to DistroURL-frontend
        run: |
          git subtree split --prefix=frontend -b temp-frontend
          git remote add frontend-origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/alucard017/DistroURL-frontend.git
          git push --force frontend-origin temp-frontend:main

      - name: Split and push backend to DistroURL-backend
        run: |
          git subtree split --prefix=backend -b temp-backend
          git remote add backend-origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/alucard017/DistroURL-backend.git
          git push --force backend-origin temp-backend:main
